// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyJ1WBlVaZTjGHwM8jJlGYkccPidbbEnQ',
    appId: '1:181724009140:web:6978c29042b63931d77de1',
    messagingSenderId: '181724009140',
    projectId: 'ecommerceflutter-d29c5',
    authDomain: 'ecommerceflutter-d29c5.firebaseapp.com',
    storageBucket: 'ecommerceflutter-d29c5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUvtx0-eyH7__GOyR_Eu7Q7sLsi7f8IAQ',
    appId: '1:181724009140:android:68d6e82e98ade261d77de1',
    messagingSenderId: '181724009140',
    projectId: 'ecommerceflutter-d29c5',
    storageBucket: 'ecommerceflutter-d29c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMSW4uj_YhcfZQmkoagN9i9-wVztZlDjw',
    appId: '1:181724009140:ios:ff6d070deb500b6fd77de1',
    messagingSenderId: '181724009140',
    projectId: 'ecommerceflutter-d29c5',
    storageBucket: 'ecommerceflutter-d29c5.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMSW4uj_YhcfZQmkoagN9i9-wVztZlDjw',
    appId: '1:181724009140:ios:ff6d070deb500b6fd77de1',
    messagingSenderId: '181724009140',
    projectId: 'ecommerceflutter-d29c5',
    storageBucket: 'ecommerceflutter-d29c5.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyJ1WBlVaZTjGHwM8jJlGYkccPidbbEnQ',
    appId: '1:181724009140:web:b1f1c5f1c23ff110d77de1',
    messagingSenderId: '181724009140',
    projectId: 'ecommerceflutter-d29c5',
    authDomain: 'ecommerceflutter-d29c5.firebaseapp.com',
    storageBucket: 'ecommerceflutter-d29c5.firebasestorage.app',
  );
}
